### ISSUE TITLE
$element.querySelectorAll is not a function

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-angular-navbar#7]
This was working and now it's not?

https://github.com/digitalbazaar/bedrock-angular-navbar/blob/master/navbar-component.js#L88

Navbar 4.x is currently broken due to this.

**Comment by dlongley** [comment]
@mattcollier, could try `$element[0].`

**Comment by mattcollier** [comment]
Fixed https://github.com/digitalbazaar/bedrock-angular-navbar/commit/450c94356d9548668050955f61776f7634341fbe
